import { Inter } from 'next/font/google'
import './globals.css'
import NewNavbar from './components/NewNavbar'
const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Website X-RPL-2',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html data-theme="cupcake" lang="en">
      <body className={inter.className}>
      <link rel="icon" href="/nexts.ico" sizes="any" />

      <NewNavbar/>
      {children}
      </body>
    </html>
  )
}
